version: 1.0.{build}
image: Visual Studio 2017

configuration: Release

nuget:
  account_feed: true
build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true

deploy:
- provider: NuGet
  api_key:
    secure: +1KK3+R5PcR/MlDWQeln3RPRG4JH+n1bL34KuJ4AUxE=
  symbol_server: https://ci.appveyor.com/nuget/wingertge-9678l6k3j3o3/api/v2/package
  artifact: /.*\.symbols\.nupkg/