version: 1.0.{build}
configuration: Release
init:
- ps: '[System.IO.File]::AppendAllText("C:\Windows\System32\drivers\etc\hosts", "`n93.184.221.200  api.nuget.org")'
  
install:
- cmd: >-
    type c:\windows\system32\drivers\etc\hosts

    ping api.nuget.org

    dotnet restore

nuget:
  account_feed: true
build:
  verbosity: minimal
artifacts:
- path: dist
  name: MemoryCore
after_build:
- cmd: dotnet publish MemoryCore --output %appveyor_build_folder%\dist

deploy:
- provider: NuGet
  server: https://ci.appveyor.com/nuget/wingertge-9678l6k3j3o3
  api_key:
    secure: +1KK3+R5PcR/MlDWQeln3RPRG4JH+n1bL34KuJ4AUxE=
  symbol_server: https://ci.appveyor.com/nuget/wingertge-9678l6k3j3o3/api/v2/package
  artifact: MemoryCore