// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MemoryApi.HttpClient
{
    using MemoryCore.JsonModels;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Users.
    /// </summary>
    public static partial class UsersExtensions
    {
            /// <summary>
            /// registers a user with the service
            /// </summary>
            /// <remarks>
            /// Validates the input posted and returns an auth token on successful
            /// registration.
            ///
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// Registration form data
            /// </param>
            public static string Register(this IUsers operations, RegisterModel body)
            {
                return operations.RegisterAsync(body).GetAwaiter().GetResult();
            }

            /// <summary>
            /// registers a user with the service
            /// </summary>
            /// <remarks>
            /// Validates the input posted and returns an auth token on successful
            /// registration.
            ///
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// Registration form data
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<string> RegisterAsync(this IUsers operations, RegisterModel body, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.RegisterWithHttpMessagesAsync(body, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
